/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FallDetectionRouteImport } from './routes/fall-detection'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicalProfileRouteImport } from './routes/medical-profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FallDetectionRoute = FallDetectionRouteImport.update({
  id: '/fall-detection',
  path: '/fall-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalProfileRoute = MedicalProfileRouteImport.update({
  id: '/medical-profile',
  path: '/medical-profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fall-detection': typeof FallDetectionRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fall-detection': typeof FallDetectionRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fall-detection': typeof FallDetectionRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fall-detection' | '/login' | '/medical-profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fall-detection' | '/login' | '/medical-profile'
  id: '__root__' | '/' | '/fall-detection' | '/login' | '/medical-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FallDetectionRoute: typeof FallDetectionRoute
  LoginRoute: typeof LoginRoute
  MedicalProfileRoute: typeof MedicalProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall-detection': {
      id: '/fall-detection'
      path: '/fall-detection'
      fullPath: '/fall-detection'
      preLoaderRoute: typeof FallDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-profile': {
      id: '/medical-profile'
      path: '/medical-profile'
      fullPath: '/medical-profile'
      preLoaderRoute: typeof MedicalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FallDetectionRoute: FallDetectionRoute,
  LoginRoute: LoginRoute,
  MedicalProfileRoute: MedicalProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
